name: Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.86.177.103 << 'EOF'
          # Ensure the directory is correct and cd into it
          cd /home/ubuntu/git_test || exit 1

          # Check if env exists, if not create it
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi

          # Activate the environment
          source env/bin/activate

          # Pull latest changes
          git pull

          # Install/Update pip and project requirements
          pip install --upgrade pip
          pip install -r requirements.txt

          # Restart the Uvicorn server
          pkill uvicorn
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          EOF
