name: Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create and activate virtual environment
        run: |
          python -m venv env
          source env/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.86.177.103 << 'EOF'
          cd /home/ubuntu/git_test
          source env/bin/activate
          git pull
          pip install -r requirements.txt
          pkill uvicorn
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          EOF
